// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared.Access.Systems;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.MedicalRecords;
using Content.Shared.StationRecords;
using Content.Shared.Traits;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.MedicalRecords;

[GenerateTypedNameReferences]
public sealed partial class MedicalRecordsConsoleWindow : FancyWindow
{
    public Action<uint?>? OnKeySelected;
    public Action<StationRecordFilterType, string>? OnFiltersChanged;
    public Action<string>? OnRecordNotesSaved;
    public Action<uint, string, string>? OnExaminationSaved;
    public Action<uint>? OnExaminationDeleted;

    private readonly EntityUid _console;
    private readonly uint _maxTitleLength;
    private readonly uint _maxNoteLength;
    private readonly IPlayerManager _players;
    private readonly IPrototypeManager _prototypes;
    private readonly AccessReaderSystem _access;

    private bool _populating;
    private bool _canEdit;
    private uint? _selectedExamination;
    private StationRecordFilterType _currentFilter = StationRecordFilterType.Name;
    private MedicalRecord? _currentRecord;

    public MedicalRecordsConsoleWindow(
        EntityUid console,
        uint maxTitleLength,
        uint maxNoteLength,
        IPlayerManager players,
        IPrototypeManager prototypes,
        AccessReaderSystem access)
    {
        RobustXamlLoader.Load(this);

        _console = console;
        _maxTitleLength = maxTitleLength;
        _maxNoteLength = maxNoteLength;
        _players = players;
        _prototypes = prototypes;
        _access = access;

        foreach (var type in Enum.GetValues<StationRecordFilterType>().Where(IsSupportedFilter))
            FilterType.AddItem(Loc.GetString($"general-station-record-{type.ToString().ToLower()}-filter"), (int) type);

        FilterType.OnItemSelected += args =>
        {
            _currentFilter = (StationRecordFilterType) args.Id;
            SendFilter();
        };
        FilterText.OnTextEntered += _ => SendFilter();
        FilterButton.OnPressed += _ => SendFilter();
        ResetFilterButton.OnPressed += _ =>
        {
            FilterText.Text = string.Empty;
            SendFilter();
        };

        RecordListing.OnItemSelected += args =>
        {
            if (_populating || RecordListing[args.ItemIndex].Metadata is not uint key)
                return;

            OnKeySelected?.Invoke(key);
        };
        RecordListing.OnItemDeselected += _ =>
        {
            if (!_populating)
                OnKeySelected?.Invoke(null);
        };

        ExaminationList.OnItemSelected += args =>
        {
            if (_populating || ExaminationList[args.ItemIndex].Metadata is not uint id)
                return;

            _selectedExamination = id;
            PopulateExamination();
        };

        SaveRecordNotesButton.OnPressed += _ =>
        {
            var notes = Rope.Collapse(RecordNotes.TextRope);
            if (_canEdit && notes.Length <= _maxNoteLength)
                OnRecordNotesSaved?.Invoke(notes);
        };

        SaveExaminationButton.OnPressed += _ =>
        {
            if (!_canEdit || _selectedExamination == null)
                return;

            var title = ExaminationTitle.Text.Trim();
            var note = Rope.Collapse(ExaminationNote.TextRope);
            if (title.Length is < 1 || title.Length > 96 || title.Length > _maxTitleLength || note.Length > _maxNoteLength)
                return;

            OnExaminationSaved?.Invoke(_selectedExamination.Value, title, note);
        };

        DeleteExaminationButton.OnPressed += _ =>
        {
            if (_canEdit && _selectedExamination != null)
                OnExaminationDeleted?.Invoke(_selectedExamination.Value);
        };
    }

    public void UpdateState(MedicalRecordsConsoleState state)
    {
        _populating = true;

        if (state.Filter != null && IsSupportedFilter(state.Filter.Type))
        {
            _currentFilter = state.Filter.Type;
            FilterText.Text = state.Filter.Value;
        }
        FilterType.SelectId((int) _currentFilter);

        RecordListing.Clear();
        RecordListing.ClearSelected();
        if (state.RecordListing != null)
        {
            foreach (var (key, name) in state.RecordListing.OrderBy(x => x.Value))
            {
                var item = RecordListing.AddItem(name);
                item.Metadata = key;
                item.Selected = key == state.SelectedKey;
            }
        }

        NoRecordsLabel.Visible = state.RecordListing == null || state.RecordListing.Count == 0;
        _canEdit = _players.LocalSession?.AttachedEntity is { } player && _access.IsAllowed(player, _console);

        NoSelectionLabel.Visible = state.Profile == null || state.MedicalRecord == null;
        RecordContainer.Visible = !NoSelectionLabel.Visible;
        _currentRecord = state.MedicalRecord;

        if (state is { Profile: { } profile, MedicalRecord: { } record })
            PopulateRecord(profile, record);
        else
            ClearRecord();

        _populating = false;
    }

    private void PopulateRecord(MedicalRecordProfile profile, MedicalRecord record)
    {
        PatientName.Text = profile.Name;
        PatientJob.Text = Loc.GetString("medical-records-console-job", ("job", profile.Job));

        var species = profile.Species;
        if (_prototypes.TryIndex<SpeciesPrototype>(profile.Species, out var speciesPrototype))
            species = Loc.GetString(speciesPrototype.Name);

        PatientSpecies.Text = Loc.GetString("medical-records-console-species", ("species", species));
        PatientAge.Text = Loc.GetString("medical-records-console-age", ("age", profile.Age));

        var traits = new List<string>();
        foreach (var traitId in record.NegativeTraits)
        {
            if (_prototypes.TryIndex<TraitPrototype>(traitId, out var trait))
                traits.Add(Loc.GetString(trait.Name));
            else
                traits.Add(traitId);
        }

        NegativeTraits.SetMessage(FormattedMessage.FromUnformatted(
            traits.Count == 0 ? Loc.GetString("medical-records-console-none") : string.Join("\n", traits)));

        RecordNotes.TextRope = new Rope.Leaf(record.Notes);
        RecordNotes.Editable = _canEdit;
        SaveRecordNotesButton.Disabled = !_canEdit;

        ExaminationList.Clear();
        ExaminationList.ClearSelected();

        if (_selectedExamination != null && record.Examinations.All(x => x.Id != _selectedExamination))
            _selectedExamination = null;

        foreach (var examination in record.Examinations.OrderByDescending(x => x.AddTime))
        {
            var text = Loc.GetString("medical-records-console-examination-list-entry",
                ("title", examination.Title),
                ("examiner", examination.ExaminerName),
                ("job", examination.ExaminerJob));
            var item = ExaminationList.AddItem(text);
            item.Metadata = examination.Id;
            item.Selected = examination.Id == _selectedExamination;
        }

        NoExaminationsLabel.Visible = record.Examinations.Count == 0;
        PopulateExamination();
    }

    private void PopulateExamination()
    {
        var examination = _currentRecord?.Examinations.FirstOrDefault(x => x.Id == _selectedExamination);
        ExaminationContainer.Visible = examination != null;
        if (examination == null)
            return;

        ExaminationMeta.Text = Loc.GetString("medical-records-console-examination-meta",
            ("time", examination.AddTime.ToString("hh\\:mm\\:ss")),
            ("examiner", examination.ExaminerName),
            ("job", examination.ExaminerJob));
        ExaminationTitle.Text = examination.Title;
        ExaminationTitle.Editable = _canEdit;
        ExaminationNote.TextRope = new Rope.Leaf(examination.Note);
        ExaminationNote.Editable = _canEdit;
        SaveExaminationButton.Disabled = !_canEdit;
        DeleteExaminationButton.Disabled = !_canEdit;
        ExaminationReport.SetMessage(FormattedMessage.FromUnformatted(examination.Report));
    }

    private void ClearRecord()
    {
        _selectedExamination = null;
        ExaminationList.Clear();
        ExaminationContainer.Visible = false;
    }

    private void SendFilter()
    {
        if (!_populating)
            OnFiltersChanged?.Invoke(_currentFilter, FilterText.Text);
    }

    private static bool IsSupportedFilter(StationRecordFilterType type)
    {
        return type is not StationRecordFilterType.DNA and not StationRecordFilterType.Species;
    }
}
