// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.UserInterface.Controls;
using Content.Shared.MedicalRecords;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.MedicalRecords;

[GenerateTypedNameReferences]
public sealed partial class MedicalNotesWindow : FancyWindow
{
    public event Action<string>? OnNotesSaved;

    public MedicalNotesWindow()
    {
        RobustXamlLoader.Load(this);
        SaveButton.OnPressed += _ => OnNotesSaved?.Invoke(Rope.Collapse(Notes.TextRope));
    }

    public void UpdateState(MedicalNotesState state)
    {
        PatientName.Text = state.PatientName;
        PatientJob.Text = Loc.GetString("medical-records-console-job", ("job", state.PatientJob));
        Notes.TextRope = new Rope.Leaf(state.Notes);
    }
}
